# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7de9c8c362eeec13e72bfe22ecabbd0ad4601121a402dfaa207d95328782ded50ec45aad8111cb3dff4b7b3d910e540ad701b735bd1ee380cdf61c276a549ee7

test:
  secret_key_base: 5fbd2d1b48e44483d5a270b2323389d514cc2a7acdc428c679960f0d9521e653f97993f5559b9db9dd085d03861b59314970ed0ac52605860d59d13efba511f6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
